# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/snowpark-db-api',
                'doc_host': 'https://Jeremy-Demlow.github.io',
                'git_url': 'https://github.com/Jeremy-Demlow/snowpark-db-api',
                'lib_path': 'snowpark_db_api'},
  'syms': {'snowpark_db_api.core': {'snowpark_db_api.core.foo': ('core.html#foo', 'snowpark_db_api/core.py')}}}
